### ISSUE TITLE
TFBroadcasterWrapper thread is initialized but it is never joined or detached in CollectionReader.cpp

### ISSUE THREAD

**Issue by anindex** [RoboSherlock/robosherlock#108]
As the topic title stated, the bug makes unit tests broken. The unit tests call and destroy the pipeline manager once for each test, which makes the thread object of TFBroadcasterWrapper goes out of scope:
`thread_ = std::thread(&TFBroadcasterWrapper::run, &broadCasterObject_);`
Therefore, the unit test are broken.

**Comment by bbferka** [comment]
@anindex thx for the notice. I'll fix this asap.

**Comment by anindex** [comment]
That is good to hear :) Hope the bug does not occupy so many part of the code

**Comment by bbferka** [comment]
@anindex you just fixed another occurence of this in  #98; could you pls check for other uses of TFBroadcaster in the source code and put those in the PR as well

**Comment by anindex** [comment]
sure :) I will make a ticket on trello for this debug
