### ISSUE TITLE
RS crashes when getting empty detect query

### ISSUE THREAD

**Issue by jworch** [RoboSherlock/robosherlock#169]
query: {"detect":""}

->

`run: /u/ropha/git/robosherlock_ws/src/robosherlock/rapidjson_ros/include/rapidjson/include/rapidjson/document.h:1081: rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::MemberBegin() [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]: Assertion IsObject() failed.`

**Comment by bbferka** [comment]
@jworch dumb mistake, not checking in the code before. Is this with the latest devel? I'll fix it with the next PR.

**Comment by jworch** [comment]
@bbferka  Ignore that for the moment. That error occurred with the older code base we use in ropha. I haven't tested that with the current version yet.
