### ISSUE TITLE
No rule to make target `/usr/lib/libapr-1.0.so'

### ISSUE THREAD

**Issue by hirennearlab** [RoboSherlock/robosherlock#2]
I am trying to install Robosherlock on my ubuntu 14.04 and ROS Indigo.

It gave following error while compiling the code:

No rule to make target `/usr/lib/libapr-1.0.so'

Please see the attached screenshot as well.

The file is existed there in the specified folder. LIBAPR_INCLUDE_DIRS is also declared in CMakeLists.txt. I followed the steps as you mentioned.

Could you please help me with the error? How to resolve it?

Thank you.

Kind regards,
Hiren.

**Comment by jworch** [comment]
Thanks for posting. As we have already figured out, the problem was that `/usr/lib/libapr-1.0.so' is a symbolic link which was broken.
