### ISSUE TITLE
error: ‘_mm_cvtph_ps’ was not declared in this scope

### ISSUE THREAD

**Issue by srinimd2005** [RoboSherlock/robosherlock#78]
Hi
I am trying to setup robosherlock on my Ubuntu pc but when I try to compile using catkin_make or rsmake i get this error.

 ../src/robosherlock/src/io/src/UnrealVisionBridge.cpp:73:94: error: ‘_mm_cvtph_ps’ was not declared in this scope
     *out = _mm_cvtph_ps(_mm_set_epi16(0, 0, 0, 0, *(in + 3), *(in + 2), *(in + 1), *(in + 0)));
                                                                                              ^
make[2]: *** [robosherlock/src/io/CMakeFiles/rs_io.dir/src/UnrealVisionBridge.cpp.o] Error 1
make[1]: *** [robosherlock/src/io/CMakeFiles/rs_io.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

Could someone help me

**Comment by bbferka** [comment]
Hi, 

could you be a bit more specific pls? As specially about your system. I did not have any problems on several machines running Ubuntu 14.04.  _mm_cvtph_ps comes with GCC so it is strange that it is not found in your case.  Coulld you check that the file is found in your include path.

**Comment by wiedemeyer** [comment]
Hi,
that are instructions to convert 16 bit floats to 32 bit floats. That is only supported on IvyBridge or newer. @bbferka Could you add a ifdef to check if it's supported or not and if it is not supported giving an error if the UnrealVisionBridge is used?

**Comment by bbferka** [comment]
Yes indeed. Was reading through the docs for this and saw that it's 3rd gen intel and up. Managed to recreate this on my i3-2365. I'll add a check in code. @srinimd2005 what is your CPU?

**Comment by srinimd2005** [comment]
Hi 
Thank you for the reply, Here are the details
System 1
Ubuntu 14.04.3
Intel® Core™ i7-3632QM CPU @ 2.20GHz
Graphics AMD Radeon HD 7600M Series

System 2
Ubuntu 14.04.5
Intel® Core™ i7 - 7500U

Both the laptops have the same error.

**Comment by tohahn** [comment]
i also have the same error while building.
error output:
```
pp: In member function ‘void UnrealVisionBridge::convertDepth(const uint16_t*, __m128*) const’:
/home/xxxx/cateros/src/perception/robosherlock/src/io/src/UnrealVisionBridge.cpp:73:94: error: ‘_mm_cvtph_ps’ was not declared in this scope
     *out = _mm_cvtph_ps(_mm_set_epi16(0, 0, 0, 0, *(in + 3), *(in + 2), *(in + 1), *(in + 0)));
                                                                                              ^
[ 91%] Building CXX object perception/robosherlock/src/io/CMakeFiles/rs_io.dir/src/visualizer.cpp.o
make[2]: *** [perception/robosherlock/src/io/CMakeFiles/rs_io.dir/src/UnrealVisionBridge.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [perception/robosherlock/src/io/CMakeFiles/rs_io.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
```

CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz

**Comment by bbferka** [comment]
All of the CPUs that you guys listed are Ivy bridge and up, so FC16 should be supported by the CPUs. Try exporting the necessary compiler flags. For instance I have an i7-4770 and I have: 

export CFLAGS="-march=core-avx2"
export CXXFLAGS="$CFLAGS"

Also try #79 and see if this works for you.

**Comment by jworch** [comment]
The latest changes to master should fix that problem, even if the flags do not work for you. Otherwise, please reopen this issue.
